// <auto-generated />
using System;
using Fulbacho.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Shared.Migrations
{
    [DbContext(typeof(FulbachoDbContext))]
    [Migration("20260428032326_ModeladoCompletoFulbacho")]
    partial class ModeladoCompletoFulbacho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fulbacho.Shared.Entities.Cancha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("boolean");

                    b.Property<int>("IdPredio")
                        .HasColumnType("integer");

                    b.Property<int>("IdSuperficie")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoCancha")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioPorHora")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdPredio");

                    b.HasIndex("IdSuperficie");

                    b.HasIndex("IdTipoCancha");

                    b.ToTable("Canchas", t =>
                        {
                            t.HasCheckConstraint("CK_Cancha_PrecioPositivo", "\"PrecioPorHora\" >= 0");
                        });
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Desafio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPropuesta")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<int?>("IdCanchaSugerida")
                        .HasColumnType("integer");

                    b.Property<int>("IdEquipoLocal")
                        .HasColumnType("integer");

                    b.Property<int>("IdEquipoVisitante")
                        .HasColumnType("integer");

                    b.Property<int>("IdEstadoDesafio")
                        .HasColumnType("integer");

                    b.Property<int>("IdZona")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCanchaSugerida");

                    b.HasIndex("IdEquipoLocal");

                    b.HasIndex("IdEquipoVisitante");

                    b.HasIndex("IdEstadoDesafio");

                    b.HasIndex("IdZona");

                    b.ToTable("Desafios");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("EscudoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdCapitan")
                        .HasColumnType("integer");

                    b.Property<int>("IdNivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdCapitan");

                    b.HasIndex("IdNivel");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.EstadoDesafio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Estados_desafio");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.EstadoReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Estados_reserva");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.JugadorEquipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .HasColumnType("integer");

                    b.Property<int>("IdJugador")
                        .HasColumnType("integer");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaUnion")
                        .HasColumnType("date");

                    b.HasKey("IdEquipo", "IdJugador");

                    b.HasIndex("IdJugador");

                    b.ToTable("Jugadores_equipos");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.NivelCompetitivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Niveles_competitivos");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Predio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("boolean");

                    b.Property<int>("IdAdmin")
                        .HasColumnType("integer");

                    b.Property<int>("IdZona")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdAdmin");

                    b.HasIndex("IdZona");

                    b.ToTable("Predios");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCancha")
                        .HasColumnType("integer");

                    b.Property<int?>("IdDesafio")
                        .HasColumnType("integer");

                    b.Property<int>("IdEstadoReserva")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioCreador")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoSena")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdCancha");

                    b.HasIndex("IdDesafio");

                    b.HasIndex("IdEstadoReserva");

                    b.HasIndex("IdUsuarioCreador");

                    b.ToTable("Reservas", t =>
                        {
                            t.HasCheckConstraint("CK_Reserva_MontosPositivos", "\"MontoSena\" >= 0 AND \"MontoTotal\" >= 0");
                        });
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Superficie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Superficies");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.TipoCancha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadJugadores")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposCancha", t =>
                        {
                            t.HasCheckConstraint("CK_TipoCancha_JugadoresValidos", "\"CantidadJugadores\" > 0");
                        });
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Cancha", b =>
                {
                    b.HasOne("Fulbacho.Shared.Entities.Predio", "Predio")
                        .WithMany("Canchas")
                        .HasForeignKey("IdPredio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fulbacho.Shared.Entities.Superficie", "Superficie")
                        .WithMany("Canchas")
                        .HasForeignKey("IdSuperficie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fulbacho.Shared.Entities.TipoCancha", "TipoCancha")
                        .WithMany("Canchas")
                        .HasForeignKey("IdTipoCancha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predio");

                    b.Navigation("Superficie");

                    b.Navigation("TipoCancha");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Desafio", b =>
                {
                    b.HasOne("Fulbacho.Shared.Entities.Cancha", "CanchaSugerida")
                        .WithMany()
                        .HasForeignKey("IdCanchaSugerida")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fulbacho.Shared.Entities.Equipo", "EquipoLocal")
                        .WithMany("DesafiosLocal")
                        .HasForeignKey("IdEquipoLocal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fulbacho.Shared.Entities.Equipo", "EquipoVisitante")
                        .WithMany("DesafiosVisitante")
                        .HasForeignKey("IdEquipoVisitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fulbacho.Shared.Entities.EstadoDesafio", "Estado")
                        .WithMany("Desafios")
                        .HasForeignKey("IdEstadoDesafio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fulbacho.Shared.Entities.Zona", "Zona")
                        .WithMany("Desafios")
                        .HasForeignKey("IdZona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanchaSugerida");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Estado");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Equipo", b =>
                {
                    b.HasOne("Fulbacho.Shared.Entities.Usuario", "Capitan")
                        .WithMany("EquiposCapitaneados")
                        .HasForeignKey("IdCapitan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fulbacho.Shared.Entities.NivelCompetitivo", "NivelCompetitivo")
                        .WithMany("Equipos")
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Capitan");

                    b.Navigation("NivelCompetitivo");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.JugadorEquipo", b =>
                {
                    b.HasOne("Fulbacho.Shared.Entities.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fulbacho.Shared.Entities.Usuario", "Jugador")
                        .WithMany("JugadorEquipos")
                        .HasForeignKey("IdJugador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Predio", b =>
                {
                    b.HasOne("Fulbacho.Shared.Entities.Usuario", "Administrador")
                        .WithMany("PrediosAdministrados")
                        .HasForeignKey("IdAdmin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fulbacho.Shared.Entities.Zona", "Zona")
                        .WithMany("Predios")
                        .HasForeignKey("IdZona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Reserva", b =>
                {
                    b.HasOne("Fulbacho.Shared.Entities.Cancha", "Cancha")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCancha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fulbacho.Shared.Entities.Desafio", "Desafio")
                        .WithMany("Reservas")
                        .HasForeignKey("IdDesafio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fulbacho.Shared.Entities.EstadoReserva", "Estado")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEstadoReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fulbacho.Shared.Entities.Usuario", "UsuarioCreador")
                        .WithMany("ReservasCreadas")
                        .HasForeignKey("IdUsuarioCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Desafio");

                    b.Navigation("Estado");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Usuario", b =>
                {
                    b.HasOne("Fulbacho.Shared.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Zona", b =>
                {
                    b.HasOne("Fulbacho.Shared.Entities.Ciudad", "Ciudad")
                        .WithMany("Zonas")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Cancha", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Ciudad", b =>
                {
                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Desafio", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Equipo", b =>
                {
                    b.Navigation("DesafiosLocal");

                    b.Navigation("DesafiosVisitante");

                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.EstadoDesafio", b =>
                {
                    b.Navigation("Desafios");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.EstadoReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.NivelCompetitivo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Predio", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Superficie", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.TipoCancha", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Usuario", b =>
                {
                    b.Navigation("EquiposCapitaneados");

                    b.Navigation("JugadorEquipos");

                    b.Navigation("PrediosAdministrados");

                    b.Navigation("ReservasCreadas");
                });

            modelBuilder.Entity("Fulbacho.Shared.Entities.Zona", b =>
                {
                    b.Navigation("Desafios");

                    b.Navigation("Predios");
                });
#pragma warning restore 612, 618
        }
    }
}
